export type Locale = "ar" | "en";
export type Localized = { ar: string; en: string };
export const local = (value: Localized, locale: Locale) => value[locale];

export const categories = [
  { id: "all", ar: "الكل", en: "All work" },
  { id: "branding", ar: "الهوية البصرية", en: "Brand identity" },
  { id: "web", ar: "المواقع الإلكترونية", en: "Websites" },
  { id: "apps", ar: "التطبيقات", en: "Digital products" },
];

export const services = [
  { id: "branding", icon: "pen", number: "01", title: { ar: "هوية لها شخصيّة", en: "Brands with character" }, description: { ar: "نكتشف جوهر علامتك ونترجمه إلى هوية بصرية متكاملة، مختلفة، وقريبة من جمهورك.", en: "We uncover the essence of your brand and bring it to life with a distinctive, connected visual identity." }, tags: { ar: ["استراتيجية العلامة", "هوية بصرية"], en: ["Brand strategy", "Visual identity"] } },
  { id: "web", icon: "code", number: "02", title: { ar: "مواقع تصنع الفارق", en: "Websites that work" }, description: { ar: "نصمّم ونطوّر مواقع سريعة وسلسة، تجمع بين جمال التجربة وقوة الأداء.", en: "Beautifully designed, thoughtfully developed websites that blend effortless experiences with powerful performance." }, tags: { ar: ["تصميم وتطوير", "متاجر إلكترونية"], en: ["Design & development", "E-commerce"] } },
  { id: "apps", icon: "layout", number: "03", title: { ar: "تجارب تحبّها الناس", en: "Experiences people love" }, description: { ar: "نحوّل الأفكار المعقّدة إلى تطبيقات وتجارب رقمية بسيطة، بديهية، وممتعة.", en: "We turn complex ideas into simple, intuitive, and delightful apps and digital experiences." }, tags: { ar: ["تجربة المستخدم", "واجهات التطبيقات"], en: ["User experience", "App interfaces"] } },
  { id: "strategy", icon: "spark", number: "04", title: { ar: "رؤية تقود للنمو", en: "A vision for growth" }, description: { ar: "نرسم معك الطريق من الفكرة إلى الانطلاق، باستراتيجية واضحة وقرارات مبنية على فهم حقيقي.", en: "From the first idea to launch day, we shape a clear strategy grounded in genuine insight." }, tags: { ar: ["استشارات إبداعية", "استراتيجية رقمية"], en: ["Creative consulting", "Digital strategy"] } },
] as const;

export type Project = {
  id: string;
  category: string;
  name: Localized;
  subtitle: Localized;
  image: string;
  color: string;
  year: string;
  duration: Localized;
  description: Localized;
  challenge: Localized;
  solution: Localized;
  deliverables: { ar: string[]; en: string[] };
};

export const projects: Project[] = [
  { id: "nawa", category: "branding", name: { ar: "نواة", en: "Nawa" }, subtitle: { ar: "جمال يبدأ من الطبيعة", en: "Beauty, rooted in nature" }, image: "/images/project-nawa.jpg", color: "#c0c5a9", year: "2026", duration: { ar: "٦ أسابيع", en: "6 weeks" }, description: { ar: "هوية تتنفس الطبيعة لعلامة عناية تؤمن بأن البساطة هي سر الجمال. من الفكرة الأولى إلى أصغر تفاصيل التغليف.", en: "A nature-inspired identity for a skincare brand that believes simplicity is the essence of beauty. From the first idea to every packaging detail." }, challenge: { ar: "بناء علامة عناية مميزة في سوق مزدحم، مع التعبير عن المكونات الطبيعية والجودة الراقية دون تعقيد.", en: "Creating a distinctive skincare brand in a crowded market, communicating natural ingredients and premium quality without complexity." }, solution: { ar: "طوّرنا لغة بصرية هادئة مستوحاة من درجات الزيتون، مع خط خاص ونظام تغليف مستدام يجعل كل منتج جزءًا من حكاية واحدة.", en: "We developed a calm olive-inspired visual language, custom typography, and a sustainable packaging system that connects every product to one story." }, deliverables: { ar: ["استراتيجية العلامة", "الشعار والهوية", "تصميم التغليف", "دليل استخدام الهوية"], en: ["Brand strategy", "Logo & identity", "Packaging design", "Brand guidelines"] } },
  { id: "madar", category: "web", name: { ar: "مدار", en: "Madar" }, subtitle: { ar: "مساحات تُلهم الحياة", en: "Spaces that inspire living" }, image: "/images/project-madar.jpg", color: "#e9dfcf", year: "2026", duration: { ar: "٨ أسابيع", en: "8 weeks" }, description: { ar: "حضور رقمي يعكس فلسفة مكتب معماري يرى في كل مساحة فرصة لحياة أجمل. تجربة هادئة تترك للعمارة مجالًا للحديث.", en: "A digital home for an architecture practice that sees every space as a chance for a better life. A calm experience that lets architecture speak." }, challenge: { ar: "تقديم مشاريع معمارية غنية بالتفاصيل بطريقة سريعة ومريحة، تحافظ على قوة الصور وسهولة الوصول للمعلومات.", en: "Presenting richly detailed architecture in a fast, intuitive experience without compromising beautiful imagery or access to information." }, solution: { ar: "صمّمنا موقعًا متجاوبًا بمعرض أعمال مرن، ومساحات بيضاء مدروسة، ونظام إدارة محتوى يتيح لفريق مدار تحديث مشاريعهم بسهولة.", en: "We designed a responsive website with a flexible portfolio, considered white space, and a content system that makes project updates effortless." }, deliverables: { ar: ["تجربة المستخدم", "تصميم الواجهات", "تطوير الموقع", "نظام إدارة المحتوى"], en: ["User experience", "Interface design", "Web development", "Content management"] } },
  { id: "nabdh", category: "apps", name: { ar: "نبض", en: "Nabdh" }, subtitle: { ar: "خطوة أقرب إلى التوازن", en: "A little closer to balance" }, image: "/images/project-pulse.jpg", color: "#dbd5ed", year: "2025", duration: { ar: "١٠ أسابيع", en: "10 weeks" }, description: { ar: "رفيق يومي يجعل الاهتمام بالصحة عادة بسيطة. تجربة تطبيق تمنحك رؤية واضحة لنشاطك، وتشجّعك على خطوات صغيرة تصنع فرقًا.", en: "A daily companion that makes wellbeing a simple habit. An app that brings clarity to your activity and celebrates small steps forward." }, challenge: { ar: "تحويل البيانات الصحية المعقدة إلى تجربة مفهومة ومحفّزة، تناسب المستخدم الجديد والمهتم بصحته على حد سواء.", en: "Turning complex health data into an understandable, motivating experience for both beginners and wellness enthusiasts." }, solution: { ar: "بدأنا بأبحاث المستخدمين، ثم بنينا نظام واجهات مرنًا وأهدافًا يومية واضحة مع تصور بسيط وجذاب للبيانات.", en: "Starting with user research, we built a flexible interface system with clear daily goals and inviting, simple data visualization." }, deliverables: { ar: ["أبحاث المستخدمين", "تصميم تجربة المستخدم", "نظام التصميم", "نموذج تفاعلي"], en: ["User research", "UX design", "Design system", "Interactive prototype"] } },
  { id: "athar", category: "branding", name: { ar: "أثر", en: "Athar" }, subtitle: { ar: "إبداع لا يشبه إلا نفسه", en: "Creativity with its own character" }, image: "/images/hero-art.jpg", color: "#e3d5e6", year: "2026", duration: { ar: "٤ أسابيع", en: "4 weeks" }, description: { ar: "هويتنا ليست مجرد شعار، بل مساحة للأفكار الجريئة. عالم بصري يجمع دفء اللون البرتقالي ومرونة الأشكال ووضوح الكلمة.", en: "Our identity is more than a logo: it is a space for bold ideas. A visual world of warm orange, flexible forms, and a clear voice." }, challenge: { ar: "التعبير عن استوديو متعدد التخصصات من خلال هوية بسيطة قابلة للتطور، توازن بين الجرأة والاحترافية.", en: "Expressing a multidisciplinary studio through a simple, evolving identity that balances boldness with professionalism." }, solution: { ar: "ابتكرنا رمزًا مرنًا مستوحى من نقطة انطلاق الفكرة، وألوانًا مفعمة بالطاقة، ولغة عربية واضحة وقريبة من الناس.", en: "We created a flexible symbol inspired by the spark of an idea, energetic colors, and a clear, approachable voice." }, deliverables: { ar: ["الهوية البصرية", "التوجه الفني", "عناصر ثلاثية الأبعاد", "الموقع الإلكتروني"], en: ["Visual identity", "Art direction", "3D assets", "Website"] } },
];

export const testimonials = [
  { quote: { ar: "لم يكن أثر مجرد فريق تصميم، بل شريكًا حقيقيًا آمن بفكرتنا. فهموا رؤيتنا من أول لقاء، وقدّموا هوية تجاوزت كل توقعاتنا.", en: "Athar wasn't just a design team, but a genuine partner who believed in our idea. They understood our vision from the first meeting and delivered an identity beyond our expectations." }, name: { ar: "سارة العبدالله", en: "Sara Alabdullah" }, role: { ar: "المؤسسة، نواة", en: "Founder, Nawa" }, initial: "س", company: "nawa" },
  { quote: { ar: "اهتمامهم بالتفاصيل يصنع فرقًا حقيقيًا. أصبح موقعنا يعكس جودة مشاريعنا، والتجربة من البداية إلى الإطلاق كانت سلسة وواضحة.", en: "Their attention to detail makes a real difference. Our website finally reflects the quality of our work, and the journey from kickoff to launch was seamless." }, name: { ar: "عمر الراشد", en: "Omar Alrashid" }, role: { ar: "الشريك المؤسس، مدار", en: "Co-founder, Madar" }, initial: "ع", company: "MADAR" },
  { quote: { ar: "حوّلوا فكرتنا المعقدة إلى تجربة بسيطة يحبها المستخدمون. فريق يجمع بين الإبداع والفهم العميق للمنتج، وسنكرر التعاون بالتأكيد.", en: "They transformed a complex idea into a simple experience people love. A team that combines creativity with a deep understanding of product. We will be back." }, name: { ar: "خالد المنصور", en: "Khalid Almansour" }, role: { ar: "مدير المنتج، نبض", en: "Product lead, Nabdh" }, initial: "خ", company: "nabdh." },
];

export const faqs = [
  { question: { ar: "كيف نبدأ العمل معًا؟", en: "How do we get started?" }, answer: { ar: "البداية بسيطة: شاركنا فكرتك عبر نموذج طلب المشروع. نراجع التفاصيل ثم نتواصل معك خلال يومَي عمل لتحديد جلسة تعارف، نفهم خلالها أهدافك ونقترح نطاق العمل المناسب.", en: "Simply share your idea through our project form. We will review it and get back to you within two business days to arrange a discovery call and suggest the right scope." } },
  { question: { ar: "كم يستغرق تنفيذ المشروع؟", en: "How long does a project take?" }, answer: { ar: "تستغرق مشاريع الهوية عادةً ٤–٦ أسابيع، والمواقع ٦–١٠ أسابيع. المدة تعتمد على نطاق المشروع، ونتفق على جدول زمني واضح قبل البداية.", en: "Brand projects typically take 4–6 weeks, and websites 6–10 weeks. Timing depends on scope, and we agree on a clear schedule before we begin." } },
  { question: { ar: "هل تعملون مع شركات خارج السعودية؟", en: "Do you work with international clients?" }, answer: { ar: "بالتأكيد. نعمل مع علامات طموحة أينما كانت. نعتمد أدوات تعاون مرنة واجتماعات دورية عن بُعد لتبقى قريبًا من كل خطوة في مشروعك.", en: "Absolutely. We partner with ambitious brands everywhere, using collaborative tools and regular remote check-ins to keep you connected to every step." } },
  { question: { ar: "ماذا يحدث بعد تسليم المشروع؟", en: "What happens after launch?" }, answer: { ar: "نُسلّم جميع الملفات المتفق عليها مع أدلة الاستخدام والتدريب اللازم، ونوفر دعمًا فنيًا للمواقع لمدة ٣٠ يومًا بعد الإطلاق، مع إمكانية الاتفاق على رعاية مستمرة.", en: "We hand over all agreed files, guidelines, and training. Websites include 30 days of technical support after launch, with ongoing care available." } },
];
